//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public bill()
        {
            this.order_detail_id = new HashSet<order_detail_id>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_address { get; set; }
        public string payment { get; set; }
        public string payment_status { get; set; }
        public Nullable<double> total { get; set; }
        public string bill_name { get; set; }
        public string bill_phone { get; set; }
        public string bill_email { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<order_detail_id> order_detail_id { get; set; }
    }
}
