//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catetory
    {
        public catetory()
        {
            this.products = new HashSet<product>();
        }
    
        public int catetory_id { get; set; }
        public string catetory_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
