//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sosEntities1 : DbContext
    {
        public sosEntities1()
            : base("name=sosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bills { get; set; }
        public DbSet<catetory> catetories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<order_detail_id> order_detail_id { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<shopping_cart> shopping_cart { get; set; }
        public DbSet<discount_info> discount_info { get; set; }
    }
}
