//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail_id
    {
        public int order_detail_id1 { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> order_id1 { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
        public virtual bill bill1 { get; set; }
    }
}
