//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.order_detail_id = new HashSet<order_detail_id>();
            this.shopping_cart = new HashSet<shopping_cart>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_ingredients { get; set; }
        public string product_description { get; set; }
        public Nullable<double> product_price { get; set; }
        public string product_image { get; set; }
        public Nullable<int> catetory_id { get; set; }
        public Nullable<double> current_price { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual catetory catetory { get; set; }
        public virtual ICollection<order_detail_id> order_detail_id { get; set; }
        public virtual discount_info discount_info { get; set; }
        public virtual ICollection<shopping_cart> shopping_cart { get; set; }
    }
}
